
version: 2

models:
  - name: titanic_2_cols_trans
    description: "Only PassengerId and Name columns from Titanic Dataset"
    columns:
      - name: PassengerId
        description: "Primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: Name
        description: "Passenger's full name"
        data_tests:
          - not_null

  - name: titanic_names
    description: "Table with passenger names parsed"
    columns:
      - name: PassengerId
        description: "Primary key for this table"
        data_tests: 
          - unique
          - not_null
      - name: FirstName
        description: "Passenger's first name"
        data_tests:
          - not_null
      - name: LastName
        description: "Passenger's last name"
        data_tests:
          - not_null
      - name: FullName
        description: "Passenger's full name"
        data_tests:
          - not_null