version: 2 # indicates dbt version

sources: 
  - name: titanic_src # reference name for schema keeping csv table
    meta: 
      external_location: 'from read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")'
    tables:
      - name: titanic_tbl # reference name for the csv table 
